name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test with pytest
      run: python3 test.py > stdout.txt 2> stderr.txt
    - name: failed test
      if: always()
      run: |
        line=$(head -n 1 stderr.txt )
        curl -d "username=${{ github.actor }}&repo=${{ github.repository }}&test=$line" -X POST https://warehouse-api.joincoded.com/github/task/pushed/python/
